export const SET_SUM = 'SET_SUM';
export const ADD_SUM = 'ADD_SUM';
export const DELETE_SUM = 'DELETE_SUM';

export const ADD_RESULT = 'ADD_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';

export const ADD_COUNT_RESULT = 'ADD_COUNT_RESULT';
export const DELETE_COUNT_RESULT = 'DELETE_COUNT_RESULT';

export const ADD_ADDITIONAL_RESULT = 'ADD_ADDITIONAL_RESULT';
export const DELETE_ADDITIONAL_RESULT = 'DELETE_ADDITIONAL_RESULT';

export const SET_CHECKED_OF_SERVICE = 'SET_CHECKED_OF_SERVICE';
export const DELETE_CHECKED_OF_SERVICE = 'DELETE_CHECKED_OF_SERVICE';

export const SET_COUNT_OF_SERVICE = 'SET_COUNT_OF_SERVICE';
export const DELETE_COUNT_OF_SERVICE = 'DELETE_COUNT_OF_SERVICE';

export const SET_ADDITIONAL_OF_CHECKED = 'SET_ADDITIONAL_OF_CHECKED';
export const DELETE_ADDITIONAL_OF_CHECKED = 'DELETE_ADDITIONAL_OF_CHECKED';

export const SET_ADDITIONAL_OF_TOTAL = 'SET_ADDITIONAL_OF_TOTAL';
export const DELETE_ADDITIONAL_OF_TOTAL = 'DELETE_ADDITIONAL_OF_TOTAL';
